# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from aruna.api.storage.services.v2 import authorization_service_pb2 as aruna_dot_api_dot_storage_dot_services_dot_v2_dot_authorization__service__pb2


class AuthorizationServiceStub(object):
    """AuthorizationService

    Contains all methods to edit and change user authorization
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateAuthorization = channel.unary_unary(
                '/aruna.api.storage.services.v2.AuthorizationService/CreateAuthorization',
                request_serializer=aruna_dot_api_dot_storage_dot_services_dot_v2_dot_authorization__service__pb2.CreateAuthorizationRequest.SerializeToString,
                response_deserializer=aruna_dot_api_dot_storage_dot_services_dot_v2_dot_authorization__service__pb2.CreateAuthorizationResponse.FromString,
                )
        self.GetAuthorizations = channel.unary_unary(
                '/aruna.api.storage.services.v2.AuthorizationService/GetAuthorizations',
                request_serializer=aruna_dot_api_dot_storage_dot_services_dot_v2_dot_authorization__service__pb2.GetAuthorizationsRequest.SerializeToString,
                response_deserializer=aruna_dot_api_dot_storage_dot_services_dot_v2_dot_authorization__service__pb2.GetAuthorizationsResponse.FromString,
                )
        self.DeleteAuthorization = channel.unary_unary(
                '/aruna.api.storage.services.v2.AuthorizationService/DeleteAuthorization',
                request_serializer=aruna_dot_api_dot_storage_dot_services_dot_v2_dot_authorization__service__pb2.DeleteAuthorizationRequest.SerializeToString,
                response_deserializer=aruna_dot_api_dot_storage_dot_services_dot_v2_dot_authorization__service__pb2.DeleteAuthorizationResponse.FromString,
                )
        self.UpdateAuthorization = channel.unary_unary(
                '/aruna.api.storage.services.v2.AuthorizationService/UpdateAuthorization',
                request_serializer=aruna_dot_api_dot_storage_dot_services_dot_v2_dot_authorization__service__pb2.UpdateAuthorizationRequest.SerializeToString,
                response_deserializer=aruna_dot_api_dot_storage_dot_services_dot_v2_dot_authorization__service__pb2.UpdateAuthorizationResponse.FromString,
                )


class AuthorizationServiceServicer(object):
    """AuthorizationService

    Contains all methods to edit and change user authorization
    """

    def CreateAuthorization(self, request, context):
        """CreateAuthorization

        Status: BETA

        This creates a user-specific attribute that handles permission for a
        specific resource 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAuthorizations(self, request, context):
        """GetAuthorization

        Status: BETA

        This gets resource specific user authorizations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteAuthorization(self, request, context):
        """DeleteAuthorization

        Status: BETA

        This creates a user-specific attribute that handles permission for a
        specific resource 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateAuthorization(self, request, context):
        """UpdateAuthorization

        Status: BETA

        This creates a user-specific attribute that handles permission for a
        specific resource 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AuthorizationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateAuthorization': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateAuthorization,
                    request_deserializer=aruna_dot_api_dot_storage_dot_services_dot_v2_dot_authorization__service__pb2.CreateAuthorizationRequest.FromString,
                    response_serializer=aruna_dot_api_dot_storage_dot_services_dot_v2_dot_authorization__service__pb2.CreateAuthorizationResponse.SerializeToString,
            ),
            'GetAuthorizations': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAuthorizations,
                    request_deserializer=aruna_dot_api_dot_storage_dot_services_dot_v2_dot_authorization__service__pb2.GetAuthorizationsRequest.FromString,
                    response_serializer=aruna_dot_api_dot_storage_dot_services_dot_v2_dot_authorization__service__pb2.GetAuthorizationsResponse.SerializeToString,
            ),
            'DeleteAuthorization': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteAuthorization,
                    request_deserializer=aruna_dot_api_dot_storage_dot_services_dot_v2_dot_authorization__service__pb2.DeleteAuthorizationRequest.FromString,
                    response_serializer=aruna_dot_api_dot_storage_dot_services_dot_v2_dot_authorization__service__pb2.DeleteAuthorizationResponse.SerializeToString,
            ),
            'UpdateAuthorization': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateAuthorization,
                    request_deserializer=aruna_dot_api_dot_storage_dot_services_dot_v2_dot_authorization__service__pb2.UpdateAuthorizationRequest.FromString,
                    response_serializer=aruna_dot_api_dot_storage_dot_services_dot_v2_dot_authorization__service__pb2.UpdateAuthorizationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'aruna.api.storage.services.v2.AuthorizationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AuthorizationService(object):
    """AuthorizationService

    Contains all methods to edit and change user authorization
    """

    @staticmethod
    def CreateAuthorization(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/aruna.api.storage.services.v2.AuthorizationService/CreateAuthorization',
            aruna_dot_api_dot_storage_dot_services_dot_v2_dot_authorization__service__pb2.CreateAuthorizationRequest.SerializeToString,
            aruna_dot_api_dot_storage_dot_services_dot_v2_dot_authorization__service__pb2.CreateAuthorizationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetAuthorizations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/aruna.api.storage.services.v2.AuthorizationService/GetAuthorizations',
            aruna_dot_api_dot_storage_dot_services_dot_v2_dot_authorization__service__pb2.GetAuthorizationsRequest.SerializeToString,
            aruna_dot_api_dot_storage_dot_services_dot_v2_dot_authorization__service__pb2.GetAuthorizationsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteAuthorization(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/aruna.api.storage.services.v2.AuthorizationService/DeleteAuthorization',
            aruna_dot_api_dot_storage_dot_services_dot_v2_dot_authorization__service__pb2.DeleteAuthorizationRequest.SerializeToString,
            aruna_dot_api_dot_storage_dot_services_dot_v2_dot_authorization__service__pb2.DeleteAuthorizationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateAuthorization(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/aruna.api.storage.services.v2.AuthorizationService/UpdateAuthorization',
            aruna_dot_api_dot_storage_dot_services_dot_v2_dot_authorization__service__pb2.UpdateAuthorizationRequest.SerializeToString,
            aruna_dot_api_dot_storage_dot_services_dot_v2_dot_authorization__service__pb2.UpdateAuthorizationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
