# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from aruna.api.storage.services.v2 import object_service_pb2 as aruna_dot_api_dot_storage_dot_services_dot_v2_dot_object__service__pb2


class ObjectServiceStub(object):
    """ObjectService

    Contains all methods that get/create or update Objects and associated resources
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateObject = channel.unary_unary(
                '/aruna.api.storage.services.v2.ObjectService/CreateObject',
                request_serializer=aruna_dot_api_dot_storage_dot_services_dot_v2_dot_object__service__pb2.CreateObjectRequest.SerializeToString,
                response_deserializer=aruna_dot_api_dot_storage_dot_services_dot_v2_dot_object__service__pb2.CreateObjectResponse.FromString,
                )
        self.GetUploadURL = channel.unary_unary(
                '/aruna.api.storage.services.v2.ObjectService/GetUploadURL',
                request_serializer=aruna_dot_api_dot_storage_dot_services_dot_v2_dot_object__service__pb2.GetUploadURLRequest.SerializeToString,
                response_deserializer=aruna_dot_api_dot_storage_dot_services_dot_v2_dot_object__service__pb2.GetUploadURLResponse.FromString,
                )
        self.GetDownloadURL = channel.unary_unary(
                '/aruna.api.storage.services.v2.ObjectService/GetDownloadURL',
                request_serializer=aruna_dot_api_dot_storage_dot_services_dot_v2_dot_object__service__pb2.GetDownloadURLRequest.SerializeToString,
                response_deserializer=aruna_dot_api_dot_storage_dot_services_dot_v2_dot_object__service__pb2.GetDownloadURLResponse.FromString,
                )
        self.FinishObjectStaging = channel.unary_unary(
                '/aruna.api.storage.services.v2.ObjectService/FinishObjectStaging',
                request_serializer=aruna_dot_api_dot_storage_dot_services_dot_v2_dot_object__service__pb2.FinishObjectStagingRequest.SerializeToString,
                response_deserializer=aruna_dot_api_dot_storage_dot_services_dot_v2_dot_object__service__pb2.FinishObjectStagingResponse.FromString,
                )
        self.UpdateObject = channel.unary_unary(
                '/aruna.api.storage.services.v2.ObjectService/UpdateObject',
                request_serializer=aruna_dot_api_dot_storage_dot_services_dot_v2_dot_object__service__pb2.UpdateObjectRequest.SerializeToString,
                response_deserializer=aruna_dot_api_dot_storage_dot_services_dot_v2_dot_object__service__pb2.UpdateObjectResponse.FromString,
                )
        self.CloneObject = channel.unary_unary(
                '/aruna.api.storage.services.v2.ObjectService/CloneObject',
                request_serializer=aruna_dot_api_dot_storage_dot_services_dot_v2_dot_object__service__pb2.CloneObjectRequest.SerializeToString,
                response_deserializer=aruna_dot_api_dot_storage_dot_services_dot_v2_dot_object__service__pb2.CloneObjectResponse.FromString,
                )
        self.DeleteObject = channel.unary_unary(
                '/aruna.api.storage.services.v2.ObjectService/DeleteObject',
                request_serializer=aruna_dot_api_dot_storage_dot_services_dot_v2_dot_object__service__pb2.DeleteObjectRequest.SerializeToString,
                response_deserializer=aruna_dot_api_dot_storage_dot_services_dot_v2_dot_object__service__pb2.DeleteObjectResponse.FromString,
                )
        self.GetObject = channel.unary_unary(
                '/aruna.api.storage.services.v2.ObjectService/GetObject',
                request_serializer=aruna_dot_api_dot_storage_dot_services_dot_v2_dot_object__service__pb2.GetObjectRequest.SerializeToString,
                response_deserializer=aruna_dot_api_dot_storage_dot_services_dot_v2_dot_object__service__pb2.GetObjectResponse.FromString,
                )
        self.GetObjects = channel.unary_unary(
                '/aruna.api.storage.services.v2.ObjectService/GetObjects',
                request_serializer=aruna_dot_api_dot_storage_dot_services_dot_v2_dot_object__service__pb2.GetObjectsRequest.SerializeToString,
                response_deserializer=aruna_dot_api_dot_storage_dot_services_dot_v2_dot_object__service__pb2.GetObjectsResponse.FromString,
                )


class ObjectServiceServicer(object):
    """ObjectService

    Contains all methods that get/create or update Objects and associated resources
    """

    def CreateObject(self, request, context):
        """CreateObject

        Status: BETA

        This creates a new object
        Initializing an object will put it in a staging area.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUploadURL(self, request, context):
        """GetUploadURL

        Status: BETA

        This is a proxy method that will call the apropriate method at dataproxy level
        This method will return a (multi-part) url that can be used to upload a
        file to S3. Part is a optional query parameter that can be used to upload a
        part of the file / multipart upload.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDownloadURL(self, request, context):
        """GetDownloadUrl

        Status: BETA

        This is a proxy method that will call the apropriate method at dataproxy level
        will return a url that can be used to download a file from S3.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FinishObjectStaging(self, request, context):
        """FinishObjectStaging

        Status: BETA

        This method completes the staging of an object.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateObject(self, request, context):
        """UpdateObject

        Status: BETA

        Objects are immutable!
        Updating an object will create a new revision for the object
        This method will put the new revision in a staging area.
        Staged objects will get a separate staging id and need to be finished
        before they can be used.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CloneObject(self, request, context):
        """CloneObject 

        Status: BETA

        This method clones an object and creates a copy in the same collection.
        This copy has a new id and revision and will not receive any updates from
        the original object.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteObject(self, request, context):
        """DeleteObject 

        Status: BETA

        Deletes the object with the complete revision history.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetObject(self, request, context):
        """GetObject 

        Status: BETA

        gets a specific Object by ID that is associated to the
        current collection By default only the latest revision of an object will be
        returned Specify a revision_number to select an older revision With the
        optional with_url boolean a download link can automatically be requested
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetObjects(self, request, context):
        """GetObjects

        Status: BETA

        Get multiple objects by ID at once
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ObjectServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateObject': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateObject,
                    request_deserializer=aruna_dot_api_dot_storage_dot_services_dot_v2_dot_object__service__pb2.CreateObjectRequest.FromString,
                    response_serializer=aruna_dot_api_dot_storage_dot_services_dot_v2_dot_object__service__pb2.CreateObjectResponse.SerializeToString,
            ),
            'GetUploadURL': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUploadURL,
                    request_deserializer=aruna_dot_api_dot_storage_dot_services_dot_v2_dot_object__service__pb2.GetUploadURLRequest.FromString,
                    response_serializer=aruna_dot_api_dot_storage_dot_services_dot_v2_dot_object__service__pb2.GetUploadURLResponse.SerializeToString,
            ),
            'GetDownloadURL': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDownloadURL,
                    request_deserializer=aruna_dot_api_dot_storage_dot_services_dot_v2_dot_object__service__pb2.GetDownloadURLRequest.FromString,
                    response_serializer=aruna_dot_api_dot_storage_dot_services_dot_v2_dot_object__service__pb2.GetDownloadURLResponse.SerializeToString,
            ),
            'FinishObjectStaging': grpc.unary_unary_rpc_method_handler(
                    servicer.FinishObjectStaging,
                    request_deserializer=aruna_dot_api_dot_storage_dot_services_dot_v2_dot_object__service__pb2.FinishObjectStagingRequest.FromString,
                    response_serializer=aruna_dot_api_dot_storage_dot_services_dot_v2_dot_object__service__pb2.FinishObjectStagingResponse.SerializeToString,
            ),
            'UpdateObject': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateObject,
                    request_deserializer=aruna_dot_api_dot_storage_dot_services_dot_v2_dot_object__service__pb2.UpdateObjectRequest.FromString,
                    response_serializer=aruna_dot_api_dot_storage_dot_services_dot_v2_dot_object__service__pb2.UpdateObjectResponse.SerializeToString,
            ),
            'CloneObject': grpc.unary_unary_rpc_method_handler(
                    servicer.CloneObject,
                    request_deserializer=aruna_dot_api_dot_storage_dot_services_dot_v2_dot_object__service__pb2.CloneObjectRequest.FromString,
                    response_serializer=aruna_dot_api_dot_storage_dot_services_dot_v2_dot_object__service__pb2.CloneObjectResponse.SerializeToString,
            ),
            'DeleteObject': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteObject,
                    request_deserializer=aruna_dot_api_dot_storage_dot_services_dot_v2_dot_object__service__pb2.DeleteObjectRequest.FromString,
                    response_serializer=aruna_dot_api_dot_storage_dot_services_dot_v2_dot_object__service__pb2.DeleteObjectResponse.SerializeToString,
            ),
            'GetObject': grpc.unary_unary_rpc_method_handler(
                    servicer.GetObject,
                    request_deserializer=aruna_dot_api_dot_storage_dot_services_dot_v2_dot_object__service__pb2.GetObjectRequest.FromString,
                    response_serializer=aruna_dot_api_dot_storage_dot_services_dot_v2_dot_object__service__pb2.GetObjectResponse.SerializeToString,
            ),
            'GetObjects': grpc.unary_unary_rpc_method_handler(
                    servicer.GetObjects,
                    request_deserializer=aruna_dot_api_dot_storage_dot_services_dot_v2_dot_object__service__pb2.GetObjectsRequest.FromString,
                    response_serializer=aruna_dot_api_dot_storage_dot_services_dot_v2_dot_object__service__pb2.GetObjectsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'aruna.api.storage.services.v2.ObjectService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ObjectService(object):
    """ObjectService

    Contains all methods that get/create or update Objects and associated resources
    """

    @staticmethod
    def CreateObject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/aruna.api.storage.services.v2.ObjectService/CreateObject',
            aruna_dot_api_dot_storage_dot_services_dot_v2_dot_object__service__pb2.CreateObjectRequest.SerializeToString,
            aruna_dot_api_dot_storage_dot_services_dot_v2_dot_object__service__pb2.CreateObjectResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetUploadURL(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/aruna.api.storage.services.v2.ObjectService/GetUploadURL',
            aruna_dot_api_dot_storage_dot_services_dot_v2_dot_object__service__pb2.GetUploadURLRequest.SerializeToString,
            aruna_dot_api_dot_storage_dot_services_dot_v2_dot_object__service__pb2.GetUploadURLResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetDownloadURL(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/aruna.api.storage.services.v2.ObjectService/GetDownloadURL',
            aruna_dot_api_dot_storage_dot_services_dot_v2_dot_object__service__pb2.GetDownloadURLRequest.SerializeToString,
            aruna_dot_api_dot_storage_dot_services_dot_v2_dot_object__service__pb2.GetDownloadURLResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def FinishObjectStaging(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/aruna.api.storage.services.v2.ObjectService/FinishObjectStaging',
            aruna_dot_api_dot_storage_dot_services_dot_v2_dot_object__service__pb2.FinishObjectStagingRequest.SerializeToString,
            aruna_dot_api_dot_storage_dot_services_dot_v2_dot_object__service__pb2.FinishObjectStagingResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateObject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/aruna.api.storage.services.v2.ObjectService/UpdateObject',
            aruna_dot_api_dot_storage_dot_services_dot_v2_dot_object__service__pb2.UpdateObjectRequest.SerializeToString,
            aruna_dot_api_dot_storage_dot_services_dot_v2_dot_object__service__pb2.UpdateObjectResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CloneObject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/aruna.api.storage.services.v2.ObjectService/CloneObject',
            aruna_dot_api_dot_storage_dot_services_dot_v2_dot_object__service__pb2.CloneObjectRequest.SerializeToString,
            aruna_dot_api_dot_storage_dot_services_dot_v2_dot_object__service__pb2.CloneObjectResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteObject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/aruna.api.storage.services.v2.ObjectService/DeleteObject',
            aruna_dot_api_dot_storage_dot_services_dot_v2_dot_object__service__pb2.DeleteObjectRequest.SerializeToString,
            aruna_dot_api_dot_storage_dot_services_dot_v2_dot_object__service__pb2.DeleteObjectResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetObject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/aruna.api.storage.services.v2.ObjectService/GetObject',
            aruna_dot_api_dot_storage_dot_services_dot_v2_dot_object__service__pb2.GetObjectRequest.SerializeToString,
            aruna_dot_api_dot_storage_dot_services_dot_v2_dot_object__service__pb2.GetObjectResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetObjects(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/aruna.api.storage.services.v2.ObjectService/GetObjects',
            aruna_dot_api_dot_storage_dot_services_dot_v2_dot_object__service__pb2.GetObjectsRequest.SerializeToString,
            aruna_dot_api_dot_storage_dot_services_dot_v2_dot_object__service__pb2.GetObjectsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
